title: Hiya Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://cstate.mnts.lt
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Real-time Caller Profile Service
      category: Uncategorized
    - name: Signals Ingestors
      category: Uncategorized
    - name: Model Calculation Service
      category: Uncategorized
    - name: User Reports Service
      category: Uncategorized
    - name: Cache Service
      category: Uncategorized
    - name: Data Analytics Service
      category: Uncategorized
    - name: FCC Report Service
      category: Uncategorized
    - name: FTC Report Service
      category: Uncategorized
    - name: Honeypot Service
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#673ab7"
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
